# -*- coding: utf-8 -*-
"""67160381.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKxXaQvQ2PmYVr4t0A0xQYxyc_U9l1aI
"""

import pandas as pd
import sqlite3
import os

# =====================================
# STEP 1 : Extract
# =====================================

df = pd.read_csv("/content/retail_logs.csv")

print("========== Original Data ==========")
print(df.head())
print()

# =====================================
# STEP 2 : Transform
# =====================================

# แปลงวันที่
df["Sale_Date"] = pd.to_datetime(
    df["Sale_Date"],
    format='mixed', # Changed format to 'mixed' to handle various date formats
    dayfirst=False
)

# คำนวณยอดขายสุทธิ
df["Total_Amount"] = (
    df["Quantity"]
    * df["Unit_Price"]
    * (1 - df["Discount_Percent"] / 100)
)

# =====================================
# Dimension : Location
# =====================================

dim_location = (
    df[
        [
            "Store_Code",
            "Branch",
            "Province",
            "Region"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_location["Location_Key"] = dim_location.index + 1

dim_location = dim_location[
    [
        "Location_Key",
        "Store_Code",
        "Branch",
        "Province",
        "Region"
    ]
]

print("========== Dimension Location ==========")
print(dim_location)
print()

# =====================================
# Dimension : Product
# =====================================

dim_product = (
    df[
        [
            "Product_Name",
            "Category"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_product["Product_Key"] = dim_product.index + 1

dim_product = dim_product[
    [
        "Product_Key",
        "Product_Name",
        "Category"
    ]
]

print("========== Dimension Product ==========")
print(dim_product)
print()

# =====================================
# Dimension : Date
# =====================================

dim_date = (
    pd.DataFrame(
        {
            "Sale_Date": df["Sale_Date"].drop_duplicates()
        }
    )
    .sort_values("Sale_Date")
    .reset_index(drop=True)
)

dim_date["Date_Key"] = dim_date.index + 1
dim_date["Day"] = dim_date["Sale_Date"].dt.day
dim_date["Month"] = dim_date["Sale_Date"].dt.month
dim_date["Year"] = dim_date["Sale_Date"].dt.year
dim_date["Weekday"] = dim_date["Sale_Date"].dt.day_name()

dim_date = dim_date[
    [
        "Date_Key",
        "Sale_Date",
        "Day",
        "Month",
        "Year",
        "Weekday"
    ]
]

print("========== Dimension Date ==========")
print(dim_date)
print()

# =====================================
# Merge Dimension Keys
# =====================================

df = df.merge(
    dim_location,
    on=[
        "Store_Code",
        "Branch",
        "Province",
        "Region"
    ]
)

df = df.merge(
    dim_product,
    on=[
        "Product_Name",
        "Category"
    ]
)

df = df.merge(
    dim_date,
    on="Sale_Date"
)

# =====================================
# Fact Table
# =====================================

fact_sales = df[
    [
        "Sale_ID",
        "Date_Key",
        "Product_Key",
        "Location_Key",
        "Quantity",
        "Unit_Price",
        "Discount_Percent",
        "Total_Amount"
    ]
]

print("========== Fact Sales ==========")
print(fact_sales)
print()

# =====================================
# STEP 3 : Load SQLite
# =====================================

# Create the output directory if it doesn't exist
output_dir = "output"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

conn = sqlite3.connect("output/retail_warehouse.db")

dim_location.to_sql(
    "Dim_Location",
    conn,
    if_exists="replace",
    index=False
)

dim_product.to_sql(
    "Dim_Product",
    conn,
    if_exists="replace",
    index=False
)

dim_date.to_sql(
    "Dim_Date",
    conn,
    if_exists="replace",
    index=False
)

fact_sales.to_sql(
    "Fact_Sales",
    conn,
    if_exists="replace",
    index=False
)

conn.close()

print("===================================")
print("Data Warehouse Created Successfully")
print("Database : retail_warehouse.db")
print("===================================")